export const GET_DATA = 'REDUCER/GET_DATA';
export const GET_ITEM = 'REDUCER/GET_ITEM';
export const EDIT_ITEM = 'REDUCER/EDIT_ITEM';
export const CREATE_ITEM = 'REDUCER/CREATE_ITEM';
export const DELETE_ITEM = 'REDUCER/DELETE_ITEM';
